export const user1 = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};
export const userSignUp = {
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
};
export const Category = {
  CATEGORY_REQUEST: "CATEGORY_REQUEST",
  CATEGORY_SUCCESS: "CATEGORY_SUCCESS",
  CATEGORY_FAILURE: "CATEGORY_FAILURE",
  CATEGORY_ADD:'CATEGORY_ADD',
  CATEGORY_ADDSUCCESS:'CATEGORY_SUCCESS',
  CATEGORY_ADDFAILURE:'CATEGORY_FAILURE'
};
export const CreateCategory ={
	
}
